### PR TITLE
207 pinpoint server implementation

### PR DESCRIPTION
**Pull request by robertvo824**
# Description

- Add `Node.js` functionality to the Pinpoint plugin.  
- Implement by using the logic found in [browser.js](https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-aws-pinpoint/src/browser.js) as a pattern.
- Use [@aws-sdk/client-pinpoint](https://www.npmjs.com/package/@aws-sdk/client-pinpoint) package to connect to the Pinpoint service. 
- Extract duplicate/shared logic into individual modules.
- Perform manual tests in our AWS analytics pipeline that sends data to Pinpoint and eventually into Redshift cluster.

## Issue Link

#207 

## Checks

- [x] Manual testing
- [x] Existing tests pass locally with my changes

## Additional Questions

1. Do you see an issue with using core logic from the browser server-side as long as browser checks are in place?

2. I did not dig into tests but is there a reason that plugins don't contain their own tests? Or do the tests in `analytics-core` cover the plugins also. If this Pinpoint server implementation works, please let me know if this is something we can add to improve coverage.

### CODE REVIEW

**Comment by robertvo824** [comment]
@DavidWells

Any chance you can give this a look? I created a sub-branch off `207-pinpoint-server-implementation` for test coverage. Performed manual testing in both browser and node. Can merge in my tests if you think that'll be helpful! Thanks!!

**Comment by DavidWells** [comment]
@robertvo824 do you have a working example?

I'm getting `error: NotFoundException: Resource not found` with my test code:

```js
// example.js
const analyticsLib = require('analytics').default
const awsPinpointPlugin = require('@analytics/aws-pinpoint').default

console.log('awsPinpointPlugin', awsPinpointPlugin)

const pinpoint = awsPinpointPlugin({
  pinpointAppId: '1111111',
  getCredentials: () => {
    return {
      accessKeyId: "a",
      secretAccessKey: "y",
      sessionToken: "x"
    }
  },
  flushInterval: 500,
  debug: true,
})

console.log('pinpoint', pinpoint)

const logger = {
  name: 'logger',
  page: ({ payload }) => {
    const { properties } = payload
    console.log('See all props properties', properties)
  }
}

const analytics = analyticsLib({
  app: 'my-app-name',
  plugins: [
    logger,
    pinpoint
  ]
})

analytics.page({
  title: 'Title xyz',
  url: `https://localhost:8000`,
  path: '/foo',
  lol: 'hi'
})

```

This is runnable via 

```
node ./example.js
```

**Comment by robertvo824** [comment]
> @robertvo824 do you have a working example?

Thanks for the response, @DavidWells! Two responses:

1. Yes, I do have a working example - we use an in-house Telemetry package that utilizes your Pinpoint plugin that we add to our front-end and back-end services. Therefore, I've been testing by linking the Node implementation to that Telemetry package. We send data from Pinpoint -> Redshift so that's how I've been manually testing.
2. Thank you for providing the snippet. I used it and it seems that the only time I ran into that `404 error: NotFoundException: Resource not found` was when I did not provide a valid `PinpointAppId`. However, I can confirm that your snippet is working when I pass in our `PinpointAppId`, `accessKeyId`, `secretAccessKey`, and `sessionToken`.
The results of the console log debug statements from a 202 response are below. Not sure why `bootstrap` is showing as `undefined` though. 

Fyi, I also did not keep the `page` function for Node implementation. We currently do not plan on tracking any page calls from server-side, but if you feel that's something you want to keep (and you would like to move forward with this PR), then I will go ahead and add it back in. Thanks!!

```js
awsPinpointPlugin [Function: awsPinpointNode]
pinpoint {
  name: 'aws-pinpoint',
  config: {
    disableAnonymousTraffic: false,
    pinpointRegion: 'us-east-1',
    eventMapping: {},
    pinpointAppId: 'our-app-id',
    getCredentials: [Function: getCredentials],
    flushInterval: 500,
    debug: true
  },
  bootstrap: undefined,
  initialize: [Function: initialize$1],
  track: [Function: track],
  identify: [Function: identify],
  loaded: [Function: loaded]
}
initSessionData {
  id: '45f02dd5-cb05-428c-95f4-12f8629aeae7',
  created: 1634564976608,
  createdAt: '2021-10-18T13:49:36.608Z',
  expires: 1634566776608,
  expiresAt: '2021-10-18T14:19:36.608Z',
  elapsed: 0,
  remaining: 1800000,
  isNew: true
}
Start brand new session
event sessionData     {"id":"ad700168-9486-46fb-abd4-03deb5a6a79c","created":1634564976610,"createdAt":"2021-10-18T13:49:36.610Z","expires":1634566776610,"expiresAt":"2021-10-18T14:19:36.610Z","elapsed":0,"remaining":1800000,"isNew":true}
See all props properties {
  title: 'Title xyz',
  url: 'https://localhost:8000',
  path: '/foo',
  lol: 'hi'
}
c0655b30-585c-44c2-a576-47c4aafaf978:_session.start
eventAttributes {
  date: '2021-10-18T13:49:36.610Z',
  sessionId: 'ad700168-9486-46fb-abd4-03deb5a6a79c',
  anonId: '50ee5abe-e0ea-4555-994c-bac4eb4126f6'
}
eventMetrics { sessionTime: 0, hour: 9, day: 2, month: 10, year: 2021 }
>>>>> PROCESS queue {
  'c0655b30-585c-44c2-a576-47c4aafaf978': {
    EventType: '_session.start',
    Timestamp: '2021-10-18T13:49:36.610Z',
    AppPackageName: 'my-app-name',
    AppTitle: 'my-app-name',
    AppVersionCode: null,
    Attributes: {
      date: '2021-10-18T13:49:36.610Z',
      sessionId: 'ad700168-9486-46fb-abd4-03deb5a6a79c',
      anonId: '50ee5abe-e0ea-4555-994c-bac4eb4126f6'
    },
    Metrics: { sessionTime: 0, hour: 9, day: 2, month: 10, year: 2021 },
    Session: {
      Id: 'ad700168-9486-46fb-abd4-03deb5a6a79c',
      StartTimestamp: '2021-10-18T13:49:36.610Z'
    }
  }
}
Endpoint {
  Attributes: {
    lastSessionDate: [ '2021-10-18T13:49:36.609Z' ],
    lastSession: [ 'f4cae6b6-8d1c-44ba-916e-7e794bacb2cb' ],
    lastPageSession: [ null ]
  },
  Demographic: {
    AppVersion: 'my-app-name@0.0.0',
    Make: 'generic server',
    Platform: 'Node.js',
    PlatformVersion: 'v14.17.2'
  },
  Location: {},
  Metrics: { sessions: 1, pageViews: 1 }
}
>>>>> PROCESS queue response {
  endpoint: {
    Attributes: {
      lastSessionDate: [Array],
      lastSession: [Array],
      lastPageSession: [Array]
    },
    Demographic: {
      AppVersion: 'my-app-name@0.0.0',
      Make: 'generic server',
      Platform: 'Node.js',
      PlatformVersion: 'v14.17.2'
    },
    Location: {},
    Metrics: { sessions: 1, pageViews: 1 },
    RequestId: '6b04cbbe-9e3c-4e5c-b72c-a2ec1cc9dbc5',
    ChannelType: undefined
  },
  response: {
    '$metadata': {
      httpStatusCode: 202,
      requestId: '7812f839-de50-431e-b0dc-71982c97ea71',
      extendedRequestId: undefined,
      cfId: 'DYMnothMfpXctwTwm3cE3zFEdm1E0zuAJdBrwhCRPPpLBNdeChTaCg==',
      attempts: 1,
      totalRetryDelay: 0
    },
    EventsResponse: { Results: [Object] }
  },
  error: undefined,
  events: [ { 'c0655b30-585c-44c2-a576-47c4aafaf978': [Object] } ]
}
```

**Comment by robertvo824** [comment]
@DavidWells 

Thanks for taking a look and adding additional commits. I will close out this PR and open up a new one repackaged with tests. However, there are some structural changes that I had to make to allow for stubbing out certain functionality. I will go ahead and create that new PR with my tests and restructure so that you can have a look.

**Pull request closed without merging**
