### PR TITLE
feat(plugins): add mixpanel

### PR DESCRIPTION
**Pull request by Oupsla**
Hello 👋 

The goal of this PR is to add a mixpanel plugin (I have based my work on what has been done for the hubspot plugin).

Some questions about what I have done : 
- I have included the mixpanel-browser package, instead of adding a script balise, it is ok or it is preferable to add a script balise (and test if window.mixpanel is already loaded ? this can lead to some mismatching versions no ?)
- I don't know how to generate the documentation, even if I have included comments with correct balises in my code, and run `npm run docs` at root folder
- There is nothing in the docs about the generation of the npm package, so I suppose that you have to do something after the merge ?

By the way, good work with this project ! It really resolves a pain to manage multiple analytics 😄

### CODE REVIEW

**Comment by DavidWells** [comment]
Nice PR!

> I have included the mixpanel-browser package, instead of adding a script balise, it is ok or it is preferable to add a script balise (and test if window.mixpanel is already loaded ? this can lead to some mismatching versions no ?)

Inside of the [initialize call](https://github.com/DavidWells/analytics/pull/98/files#diff-c1cdad41e5b1ccf6cd76b1ec2748458aR21) you want to have the mixpanel JS loading logic. You can wrap this in a check to see if the user has already loaded it externally and if so noOp the loading logic. 

Plugins are meant to "just work"™ and that includes loading the third party analytics script, if it doesn't already exist on the page.

> I don't know how to generate the documentation, even if I have included comments with correct balises in my code, and run npm run docs at root folder

In the [readme](https://github.com/DavidWells/analytics/pull/98/files#diff-2b3ce2b8718e3ce07b5d1fc240fe47b9R10) you want to add the comment:

```
<!-- AUTO-GENERATED-CONTENT:START (PLUGIN_DOCS) -->
docs will generate here
<!-- AUTO-GENERATED-CONTENT:END (PLUGIN_DOCS) -->
```

See https://github.com/DavidWells/analytics/blame/master/packages/analytics-plugin-google-analytics/README.md#L49 for example

**Comment by Oupsla** [comment]
@DavidWells thanks for info 👍 

Init script added + docs generated + alias method added

**Comment by DavidWells** [comment]
Looks good to me!

Merging and releasing 😎

**Comment by DavidWells** [comment]
Released! https://www.npmjs.com/package/@analytics/mixpanel

Also, live on the docs site https://getanalytics.io/plugins/mixpanel/

Many thanks for your contribution!

**Pull request merged**
