### PR TITLE
Snowplow v3 update

### LINKED ISSUE #202: Bump / Upgrade Snowplow to v3 (RENAMED)
I need to be able to enable the Snowplow Debugger Plugin which seems to not ship with the snowplow tracker (sp.js) but only with their [Snowplow plugins.umd.zip](https://github.com/snowplow/snowplow-javascript-tracker/releases?after=%40snowplow%2Fbrowser-plugin-error-tracking_v3.1.2)

@DavidWells How would the Analytics wrapper enable me to load additional Snowplow plugins that are not already included in sp.js ?

The way that the GetAnalytics seems to handle existing plugins is with the `     instance.plugins.snowplow.enableActivityTracking({        })` 

As per Snowplow [documentation here](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-trackers/javascript-tracker/javascript-tracker-v3/plugins/debugger/) they suggest to do the following

```
window.snowplow('addPlugin', 
  "https://cdn.jsdelivr.net/npm/@snowplow/browser-plugin-debugger@latest/dist/index.umd.min.js",
  ["snowplowDebugger", "DebuggerPlugin"]
);
```

When trying to do `instance.plugins.snowplow.enableDebugger()` then we will get a 
"AppContext.tsx:139 Uncaught (in promise) TypeError: instance.plugins.snowplow.enableDebugger is not a function"

However with `instance.plugins.snowplow.enableFormTracking()` this works because it ships with sp.js

### PR DESCRIPTION
**Pull request by paulboocock**
Closes #202

I've switched the Snowplow plugin to use `@snowplow/browser-tracker` so theres no need to load an external assets (e.g. `sp.js`). However, I had failing builds due to the old commonjs rollup plugin, which was failing on a number of older commonjs dependencies the `browser-tracker` uses. Upgrading fixes this, but I had to upgrade rollup to v2 as well. I appreciate that has a knock on consequence on every plugin but I've done some testing and everything seems ok from what I can see (and all the assets I tested came out a few kb smaller too 🎉 ).

If the rollup upgrade isn't desirable, let me know and I can quite switch this to continue using the v3 `sp.js` rather than bundling the browser-tracker package.

### CODE REVIEW

**Comment by markojak** [comment]
@paulboocock Thanks for doing this PR. Is the switch from the "snowplow-tracker" package due to this being deprecated? 
I'm curious what implications this update and switch to browser-tracker can have.

Some Questions:

1. Would there be a scenario where you would need to specify which version of the collector to use? How can you do this via the browser-tracker package (or is it linked to the version)
(Self hosting the JS tracker as per this [doc](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-trackers/javascript-tracker/self-hosting-the-javascript-tracker/) seems to have various advantages.

2. I was under the impression the JS Tracker is specifically for async loading to prevent page load issues. How would page load speeds be affected now with the switch to the browser-tracker package?

3. Browser-tracker seems to support all the plugins required which is great. How would they be loaded? 
For example would you need to install them first like `"@snowplow/browser-plugin-form-tracking": "^3.1.5",` and then load them in the plugins [] under the `snowplowPlugin({})` ? 

Would you be able to share an example I could checkout and test?

@DavidWells Is there any way to expedite this PR? I think a lot of people are using Snowplow and very few still with v2 of the tracker.

**Comment by DavidWells** [comment]
@markojak I'm having trouble building these changes with the roll-up changes.

I've been meaning to refactor this projects dep setup for a while using `pnpm` instead of lerna. 

The current setup is actually blocking full CI for releases and such 😅

You might want to inline this newer version while all of that gets sorted out

**Comment by paulboocock** [comment]
If you want to switch to `pnpm`, give https://rushjs.io/ a try! I'll revert this back to something that still requires `sp.js` to be loaded.

**Comment by paulboocock** [comment]
> @paulboocock Thanks for doing this PR. Is the switch from the "snowplow-tracker" package due to this being deprecated? I'm curious what implications this update and switch to browser-tracker can have.
> 
> Some Questions:
> 
>     1. Would there be a scenario where you would need to specify which version of the collector to use? How can you do this via the browser-tracker package (or is it linked to the version)
>        (Self hosting the JS tracker as per this [doc](https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-trackers/javascript-tracker/self-hosting-the-javascript-tracker/) seems to have various advantages.
> 
>     2. I was under the impression the JS Tracker is specifically for async loading to prevent page load issues. How would page load speeds be affected now with the switch to the browser-tracker package?
> 
>     3. Browser-tracker seems to support all the plugins required which is great. How would they be loaded?
>        For example would you need to install them first like `"@snowplow/browser-plugin-form-tracking": "^3.1.5",` and then load them in the plugins [] under the `snowplowPlugin({})` ?
> 

Is the switch from the "snowplow-tracker" package due to this being deprecated?
- Yeah, `@snowplow/node-tracker` is the same package, its just part of the same code base as the `@snowplow/browser-tracker` now which means its easier to keep it all up to date.

1. The browser-tracker would be linked at a specific version to a specific version of this package. All the benefits of self hosting the js tracker would apply here, because this code would all be bundled into your application (which is effectively the same as self hosting it).
2. This would increase the size of your application, although probably not by too much. Bundling your tracking library directly has a number of benefits, mainly that you can't be blocked by adblockers from loading and you'll never miss a page view due to the user navigating before the `sp.js` asset loads.
3. Yeah, thats pretty much how I added support for them.

**Comment by markojak** [comment]
@paulboocock and @DavidWells - You guys both rock for pushing this forward. Thanks Paul for making sure that this happens - I'm sure you have a lot going on.

@DavidWells I'm a bit of a noob at this but not sure what you mean with "inline this newer version"? How would I use this newer version with our project?

I'm not really understanding the challenge here because I don't have the experience with a mono-repo like Analytics but it seems to me that the browser-tracker version is better so maybe keep the version you've rolled up @paulboocock ?

> @markojak I'm having trouble building these changes with the roll-up changes.
> 
> I've been meaning to refactor this projects dep setup for a while using `pnpm` instead of lerna.
> 
> The current setup is actually blocking full CI for releases and such 😅
> 
> You might want to inline this newer version while all of that gets sorted out

**Comment by paulboocock** [comment]
> I'm not really understanding the challenge here because I don't have the experience with a mono-repo like Analytics but it seems to me that the browser-tracker version is better so maybe keep the version you've rolled up @paulboocock ?

We can't at the moment, because it doesn't build correctly using rollup v1 (one of the rollup plugins, commonjs, has a huge panic attack). I believe what @DavidWells means with inline this newer version is to use the same approach as we did with v2, but require a v3 sp.js. The risk here will be the breaking change, as you'll need to update your `sp.js` to a v3 tracker alongisde the npm package.

**Comment by markojak** [comment]
@paulboocock 

This is how we are loading Analytics + Snowplow right now (see below). We are using the 3.1.1 of the JS Tracker so that means we are already doing this? (https://cdn.secta.ai/3.1.1/q4E5lh.js) 

So @DavidWells What is the action plan then with regard to upgrading to v3 via browser-tracker? 
Can I do anything to help push this forward?

```
            const analytics = Analytics({
                app: 'secta',
                debug: client.debug,
                plugins: [
                    snowplowPlugin({
                        name: 'snowplow',
                        scriptSrc: 'https://cdn.secta.ai/3.1.1/q4E5lh.js',
                        collectorUrl: 'sp.secta.ai',
                        debug: client.debug, // Debug from API
                        trackerSettings: {
                            appId: spAppId,
                            discoverRootDomain: true,
                            cookieName: '_secta_',
                            cookieSameSite: 'Lax',
                            contexts: {
                                webPage: true,
                                gaCookies: true,
                                performanceTiming: true, // Analytics PerformanceTiming: https://getanalytics.io/plugins/snowplow/
                            },
                        },
                    }),
                ],
            })
```

**Comment by paulboocock** [comment]
Yes you are already doing this. However, using v3 and the current version of this plugin will have a number of incompatible API calls, only simple page view calls and such will likely be working. I'd honestly suggest using v2.18.2 with this plugin, its fundamentally the same and also up to date as we continued supporting v2 (at least for a little while longer).

**Comment by markojak** [comment]
@paulboocock Just a note of thanks for all your input and pushing to get this bumped to V3. For now (as suggested) I've downgraded to `2.18.2` and it seems to be working fine. Using the following plugins to get my basic analytics going.

I don't seem to notice anything different but still looking forward to the browser-tracker version bump as you've done the PR

```
                    instance.plugins.snowplow.enableActivityTracking(10, 10)
                    instance.plugins.snowplow.enableLinkClickTracking()
                    instance.plugins.snowplow.enableFormTracking()
```

**Comment by markojak** [comment]
@DavidWells Any progress on this one or a plan for the upgrade date?

**Comment by DavidWells** [comment]
Finally had time to update the build/tooling.

This is released via `@analytics/snowplow@0.3.0` 

Thanks for all the hard work on it ❤️

**Pull request merged**
