### PR TITLE
feat: 🎸 add custom domain support to simple analytics

### PR DESCRIPTION
**Pull request by xorob0**

### CODE REVIEW

**Comment by adriaandotcom** [comment]
Thanks! While you are at it. Could you change the default script to `scripts.simpleanalyticscdn.com/latest.js`?

**Comment by xorob0** [comment]
@adriaanvanrossum done ;)

**Comment by adriaandotcom** [comment]
Perfect! 🙌

**Comment by DavidWells** [comment]
Released with `@analytics/simple-analytics@0.3.0`

**Comment by adriaandotcom** [comment]
Thanks David! ❤️

**Pull request merged**
