### PR TITLE
Update to support ReactNative

### PR DESCRIPTION
**Pull request by chrisdrackett**

### CODE REVIEW

**Comment by chrisdrackett** [comment]
Not sure if this is the best way forward vs. just treating React Native like a server implementation.

**Comment by chrisdrackett** [comment]
so this takes care of the core stuff, but now the issue is that react native is still going to try and use the `browser` version of any plugin. As most of these include web only code is still isn't possible to track anything in react native. Curious if you have thoughts on the best way forward here, I'm still a little fuzzy on how the decision on which of this files to use is made

**Comment by DavidWells** [comment]
Just tested this out. Looks good.

Going to merge and release for ya. 

I'm still trying to get to the bottom of whats up with React native using browser version of the module 😃https://twitter.com/DavidWells/status/1252422868027142157

**Comment by DavidWells** [comment]
> react native is still going to try and use the browser version of any plugin

Ah yeah good point... still need to figure out

**Comment by DavidWells** [comment]
Ok updated to support in analytics@0.3.5

Also, typescript types are now republished 😃

**Pull request merged**
