### PR TITLE
Allow more config options within Simple Analytics

### PR DESCRIPTION
**Pull request by adriaandotcom**
Extra options:

| Option                                    | description                                                                                                             |
| :---------------------------------------- | :---------------------------------------------------------------------------------------------------------------------- |
| `customDomain` <br/>_optional_ - string   | Custom domain for simple analytics script. https://docs.simpleanalytics.com/script                                      |
| `collectDnt` <br/>_optional_ - boolean    | Allow collecting DNT visitors. https://docs.simpleanalytics.com/dnt                                                     |
| `mode` <br/>_optional_ - string           | Allow hash mode. https://docs.simpleanalytics.com/hash-mode                                                             |
| `ignorePages` <br/>_optional_ - string    | Add ignore pages. https://docs.simpleanalytics.com/ignore-pages                                                         |
| `saGlobal` <br/>_optional_ - string       | Overwrite SA global for events. https://docs.simpleanalytics.com/events#the-variable-sa_event-is-already-used           |
| `autoCollect` <br/>_optional_ - boolean   | Disable auto collect if needed. https://docs.simpleanalytics.com/trigger-custom-page-views#use-custom-collection-anyway |
| `onloadCallback` <br/>_optional_ - string | Allow onload callback. https://docs.simpleanalytics.com/trigger-custom-page-views#use-custom-collection-anyway          |
| `hostname` <br/>_optional_ - string       | Allow overwriting domain name. https://docs.simpleanalytics.com/overwrite-domain-name                                   |

### CODE REVIEW

**Comment by adriaandotcom** [comment]
Not sure if I can fix the error in the deploy script: https://app.netlify.com/sites/gosquared-demo/deploys/618a817f039b0e00089c787d

**Comment by DavidWells** [comment]
Thanks for the updates!

Released via `@analytics/simple-analytics@0.3.2`

**Comment by DavidWells** [comment]
https://getanalytics.io/plugins/simple-analytics/#configuration-options-for-browser

**Comment by adriaandotcom** [comment]
Thanks David!

**Pull request merged**
