### PR TITLE
allow gtm to use custom dataLayer

### PR DESCRIPTION
**Pull request by joonasmattila**
It seems loaded-function doesn't get config as a param so had to use local variable here.

### CODE REVIEW

**Comment by DavidWells** [comment]
Looks good to me. Thanks for adding this.

I've always used 'dataLayer' 😃

What do you typically name things?

**Comment by DavidWells** [comment]
This is released with `@analytics/google-tag-manager@0.3.0`

**Comment by DavidWells** [comment]
Docs also updated on https://getanalytics.io/plugins/google-tag-manager/#custom-name-for-datalayer-object

**Comment by joonasmattila** [comment]
> Looks good to me. Thanks for adding this.
> 
> I've always used 'dataLayer' 😃
> 
> What do you typically name things?

Well, dataLayer is a good name for a data layer. 😄 In my case, we had to use two GTM-instances with their own data layers. Thanks for a great library!

**Pull request merged**
